
#============================#
#===== Project settings =====#
#============================#

# ��Ʒ����Ŀ���ơ��汾����Ȩ���
productName: YoGee
productVersion: V1.0
copyrightYear: 2018


#============================#
#===== Database settings ====#
#============================#

# ���ݿ�����
jdbc:

  # Mysql ���ݿ�����
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/yogee?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: root
  testSql: SELECT 1


#============================#
#===== System settings ======#
#============================#



#============================#
#=== FileUpload settings ====#
#============================#



#============================#
#======= wx settings ========#
#============================#
